config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

    get '/jaunumi/:id', to: "posts#show", :as => 'jaunums'
    get '/jaunumi', to: "posts#index", :as => 'jaunumi'

    get '/lapa/:id', to: "pages#show", :as => 'lapa'
    get '/galerijas/:id', to: "albums#show", :as => 'galerija'
    get '/galerijas', to: "albums#index", :as => 'galerijas'

    get ':page_id', :as => :page, 
                    :via => :get, 
                    :controller => :pages, 
                    :action => :show

    resources :pages, only: [:show, :index] do
      member do
        get :show
      end  
    end  

    resources :contact_forms, only: [:create] 
    resources :member_uploads, only: [:create] 

    root :to => 'pages#show', :id => Page.where(:visible =>  true).order("position asc").first.slug if (ActiveRecord::Base.connection.table_exists? 'pages' and Page.count > 0)
    
    get '*path' => redirect('/')
end

app/models/album.rb
#encoding: utf-8
class Album < ActiveRecord::Base

  attr_accessor :multi_images
  
  has_attached_file :cover_image, :styles => {:thumb => 'x70', :medium => '310x160#'}, :default_url => "/assets/default_page_image.jpg"
  # validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :cover_image, :content_type => /\Aimage/

  belongs_to :album_category

  has_many :album_images, :dependent => :destroy
  accepts_nested_attributes_for :album_images,:allow_destroy => true

  def cover
    obj = nil
    if self.cover_image.present?
      obj = self.cover_image  
    else  
      if self.main_image.present?
        obj = album_images.where(:id => self.main_image).last.image
      else  
        obj = album_images.order("position asc").first.image
      end 
    end 
  end 

  
end

app/controllers/albums_controller.rb
#encoding: utf-8
class AlbumsController < ApplicationController
  before_filter :set_top_page

  def set_top_page
    @top_pages = Page.where(:ancestry => nil, :visible => true).order("position asc")
    @current_page = Page.where(:visible => true).where(:ancestry => nil).where(:page_link => '/galerijas').last
    @selected_top_page = (@current_page.parent.present? ? @current_page.parent : @current_page) rescue nil
  end 

  def index
    @albums = Album.order("created_at desc").page(params[:page]).per(5)
    @page_title = 'Galerijas'
    render "albums/index", :layout => "application"
  end 

  def show
    @album = Album.find(params[:id])
    @page_title = @album.title || 'Galerija'
    @album_images = @album.album_images.page(params[:page]).per(20)
  end 

end

app/views/admin/albums/_inline_form.html.erb
<%= semantic_form_for album, multipart: true, :url => admin_album_path(:id => album.id), :class => "nobottommargin", :method => :put, :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :multi_images, :as => :file, :label => false, :input_html => {:multiple => true} %>
    <%= f.input :id, :as => :hidden, :value => album.id %>
  <% end %>  

  <%= f.action :submit, :as => :input, :label => "Pievienot", :button_html =>{:class => "button button-3d button-black nomargin", :id => "register-form-submit"} %>
<% end %>      

app/views/admin/albums/_inline_form_title.html.erb
<%= semantic_form_for album, multipart: true, :url => admin_album_path(:id => album.id), :class => "nobottommargin", :method => :put, :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :title, :label => "Nosaukums" %>
    <%= f.input :id, :as => :hidden, :value => album.id %>
  <% end %>  

  <%= f.action :submit, :as => :input, :label => "Nomainīt", :button_html =>{:class => "button button-3d button-black nomargin", :id => "register-form-submit"} %>
<% end %>      