config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

    get '/jaunumi/:id', to: "posts#show", :as => 'jaunums'
    get '/jaunumi', to: "posts#index", :as => 'jaunumi'

    get '/lapa/:id', to: "pages#show", :as => 'lapa'
    get '/galerijas/:id', to: "albums#show", :as => 'galerija'
    get '/galerijas', to: "albums#index", :as => 'galerijas'

    get ':page_id', :as => :page, 
                    :via => :get, 
                    :controller => :pages, 
                    :action => :show

    resources :pages, only: [:show, :index] do
      member do
        get :show
      end  
    end  

    resources :contact_forms, only: [:create] 
    resources :member_uploads, only: [:create] 

    root :to => 'pages#show', :id => Page.where(:visible =>  true).order("position asc").first.slug if (ActiveRecord::Base.connection.table_exists? 'pages' and Page.count > 0)
    
    get '*path' => redirect('/')
end

app/views/common/_controls.html.erb
<% path_up = "move_up_admin_#{subject.class.name.underscore.downcase}_path(#{subject.id})" %>

<% path_down = "move_down_admin_#{subject.class.name.underscore.downcase}_path(#{subject.id})" %>


<div class="controls">
  <%= link_to("&uarr;".html_safe, eval(path_up), :class => subject.show_up_arrow? ? "disabled_link" : "") unless subject.show_up_arrow? %>
  <%= link_to("&darr;".html_safe,  eval(path_down), :class => subject.show_down_arrow? ? "disabled_link" : "" ) unless subject.show_down_arrow? %>

</div>

app/views/common/_footer.html.erb
<footer class="main-footer wow fadeInUp">
    <div class="container">
      <div class="col-md-8 col-sm-12">
        <div class="row">
          <nav class="footer-nav">
            <ul>
              <% @top_pages.each_with_index do |page,index| %>
                <li><a href="<%= lapa_path(page.slug) %>" class="animsition-link link"><%= page.title  %></a></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>

      <div class="col-md-4 col-sm-12" style="text-align:right">
        <div class="row">
          <div class="uppercase gray-text">
           <%=  Setting.uncached_value_for('copyright')  %>
          </div>
          <ul class="social-icons" style="margin-top:30px;float:right">
            <li><a href="#"><i class="icon ion-social-facebook"></i></a></li>
            <li><a href="#"><i class="icon ion-social-twitter"></i></a></li>
            <li><a href="#"><i class="icon ion-social-youtube"></i></a></li>
            <li><a href="#"><i class="icon ion-social-linkedin"></i></a></li>
            <li><a href="#"><i class="icon ion-social-pinterest"></i></a></li>
            <li><a href="#"><i class="icon ion-social-instagram"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/common/_header.html.erb
  <header class="main-header">
    <div class="container">
      <div class="logo">
        <a href="/"><img src="<%= image_path 'img/logo.png' %>" alt="logo"></a>
      </div>

      <div class="menu">
        <!-- desktop navbar -->
        <nav class="desktop-nav">
          <ul class="first-level">
            <% @top_pages.each_with_index do |page,index| %>
             <% if page.has_children? %>
               <ul class="second-level">
                 <% page.children.where(:visible => true).order("position asc").each do |child| %> 
                    <li><a href="<%= lapa_path(child.slug) %>" class="animsition-link"><%= child.title %></a></li>
                 <% end %>   
              </ul>
             <% else %>
                <li><a href="<%= lapa_path(page.slug) %>" class="animsition-link"><%= page.title  %></a></li>
             <% end %>
            <% end %> 
          </ul>
        </nav>
        <!-- mobile navbar -->
        <nav class="mobile-nav"></nav>
        <div class="menu-icon">
          <div class="line"></div>
          <div class="line"></div>
          <div class="line"></div>
        </div>
      </div>
    </div>
  </header>

app/views/common/_member_upload_form.html.erb
<section class="green-section wow fadeInUp" style="padding:50px 0">
  <div class="container">
    <div class="col-md-6 col-sm-12">
      <div class="row">
        <span class="white-text montserrat-text" style="font-size:20px;display:block;">
         Ja arī Tev ir bīgls, nepalaid garām - tiekamies 22.maijā, ekporta ielas suņu pastaigu laukumā!
        </span>
        <a href="https://www.facebook.com/bigliemlv/?fref=ts" class="btn white button-to-fb" target='_blank' style="margin-top:30px"><span>ATZĪMĒJIES FACEBOOK</span></a>
      </div>
    </div>

    <div class="col-md-6 col-sm-12">
        <div class="row">
          <div class="white-section" style="padding:20px">
            <span class="montserrat-text uppercase" style="font-size:24px">Iepazīstini ar savu bīglu pārējos saostīšanās dalībniekus</span>
            <p>
              Pievieno sava mīluļa foto, pieraksti viņa vārdu un pievienojies pārējiem bīgliņiem sadaļā "dalībnieki"
            </p>
            <form action="/member_uploads" method="post" multipart="true" enctype="multipart/form-data" data-multipart="false" novalidate="novalidate">
              <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
              <div class="input_1" style="margin-bottom:10px">
                <input type="text" name="member_upload[dog_name]">
                <span>Bīgla vārds</span>
              </div>
              
                <span style='font-size: 14px;color: #9a9a9a;'>BILDE</span>
                <input type="file" name="member_upload[image]">


              <button type="submit" class="btn green" style="margin-top:20px"><span>pievienot</span></button>
            </form>
          </div>
        </div>
      </div>
  </div>
</section>

app/views/common/_menu.html.erb
                   <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                    <!-- Logo
                    ============================================= -->
                    <div id="logo">
                       <!--  <a href="/" class="retina-logo" data-dark-logo='<#%= asset_path("logo/logo_#{locale.to_s}.png") %>'><img src='<#%= asset_path("logo/logo_#{locale.to_s}.png") %>' alt="Logo"></a> -->
                        <a href="/" class="standard-logo" data-dark-logo="<%= asset_path("logo/spo_logo.png") %>"><img src='<%= asset_path("logo/spo_logo.png") %>' alt="Logo"></a>
                        <a href="/" class="retina-logo" data-dark-logo='<%= asset_path("logo/spo_logo.png") %>'><img src='<%= asset_path("logo/spo_logo.png") %>' alt="Logo"></a>
                    </div><!-- #logo end -->

                    <!-- Primary Navigation
                    ============================================= -->
                    <nav id="primary-menu">

                        <ul>


                            <% @top_pages.each_with_index do |page,index| %>
                               <% if page.has_children? %>
                                    <li class=" <%= 'selected_top_menu' if @selected_top_page && @selected_top_page.id == page.id %>"><a href="<%= page_path(page.slug) %>"><div><%= page.title %></div></a>
                                        <ul>
                                            <% page.children.where(:visible => true).order("position asc").each do |child| %>
                                                <li class="<%= 'selected'  if @current_page && @current_page.id == child.id  %>" ><a href="<%= page_path(child.slug) %>"><div><%= child.title %></div></a></li>
                                            <% end %>    
                                        </ul>
                                    </li>
                                <% else %>
                                    <li>
                                       <li class="<%= 'current' if page.slug == params[:id] %>">
                                            <a href="<%= page_path(page.slug) %>"><div><%= page.title %></div></a>
                                        </li>
                                    </li>
                                <% end %>
                            <% end %>   
                           <% if false %> 
                               <% if current_user %>
                                            <li class="social_login">
                                                <a id="draugiem" href="<%= my_products_pages_path %>" title="<%= "#{current_user.name} (#{current_user.products.count})" %>" style="padding-right:0">
                                                     <!-- <div> -->
                                                        <i class="i-rounded icon-user"></i>
                                                
                                                    <!-- </div> -->
                                                </a>
                                            </li>
                                         </li>
                                         <li class="social_login">
                                                <a id="draugiem" href="<%= signout_path %>"><div><%= "Iziet" %></div></a>
                                            </li>
                                         </li>
                                    <% else %>
                                         <li>
                                          <!--  <li class="social_login">
                                                <a id="draugiem" href="<#%= signin_path(:provider => 'draugiem') %>"><div><4%= "draugiem.lv" %></div></a>
                                            </li> -->
                                         </li>
                                         <li>
                                           <li class="social_login">
                                                <a id="facebook" href="<%= signin_path(:provider => 'facebook') %>"><div><%= "facebook" %></div></a>
                                            </li>
                                         </li>
                                         <li>
    <!--                                        <li class="social_login">
                                                <a id="twitter" href="<$%= signin_path(:provider => 'twitter') %>"><div><$%= "twitter" %></div></a>
                                            </li> -->
                                         </li>
                                    <% end %> 
                            <% end %>         
                                    
                        </ul>

                        


                    </nav><!-- #primary-menu end -->